apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
spec:
  selector:
    matchLabels:
      run: loadgen
  replicas: 1
  template:
    metadata:
      labels:
        run: loadgen
    spec:
      containers:
      - name: loadgen
        image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.5
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
--- 
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: loadgen
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loadgen
  minReplicas: 1
  maxReplicas: 8
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: loadgen
  labels:
    run: loadgen
spec:
  ports:
  - port: 8080
  selector:
    run: loadgen
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loadgen
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: 192-168-64-11.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: loadgen
            port: 
              number: 8080
